### ISSUE TITLE
Add support for gatsby-transformer-remark?

### ISSUE THREAD

**Issue by KyleAMathews** [alexmacarthur/gatsby-source-dropbox-paper#2]
You can create nodes with the mediaType set to `text/markdown` and then you'll automatically be able to query the markdown transformed to html!

**Comment by alexmacarthur** [comment]
Whoa, that's perfect. Updates to come!

**Comment by alexmacarthur** [comment]
Fixed by 343d8b118711fae48bcfa437962f6f1ee77f1318.
